### ISSUE TITLE
Stoi not declared 

### ISSUE THREAD

**Issue by cbruce1** [RobinsonK/Robinson_CSCI2270_FinalProject#1]
Hello, I'm running your program on the CU VM. In your menu function I'm getting an error that "stoi" is not declared. I can't figure out how to fix this and run the program.
Thanks, Chloe

**Comment by RobinsonK** [comment]
Program requires c++11. Sorry if that was not clear in the ReadMe. 

To compile in terminal:
g++ -std=c++11 main.cpp Playlist.cpp Playlist.h

Then run the a.out file
./a.out

**Comment by cbruce1** [comment]
Thanks I will try this.
